apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    role: monitor
    tier: backend
  namespace: grafana
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana
    role: monitor
    tier: backend
